
services:
  proxy:
    image: pambrose/prometheus-proxy:1.14.1
    ports:
      - 8092:8092
      - 8080:8080
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  agent:
    image: pambrose/prometheus-agent:1.14.1
    ports:
      - 8083:8083
      - 8093:8093
    environment:
      AGENT_CONFIG: "simple.conf"
    volumes:
      - ./simple.conf:/app/simple.conf




